# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcus', '0002_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='followup',
            field=models.BooleanField(default=False, help_text='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u044c \u043f\u043e \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u0435 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f \u043e \u043d\u043e\u0432\u044b\u0445 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u044f\u0445 \u0432 \u044d\u0442\u043e\u0439 \u0442\u0435\u043c\u0435'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='language',
            field=models.CharField(choices=[(b'ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), (b'en', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439')], max_length=2, verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[(b'comment', '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'), (b'pingback', 'Pingback')], max_length=20),
        ),
    ]
